export const plans = {
	basic: {
		type: 'subscription',
		stripePricingId: process.env.NEXT_PUBLIC_STRIPE_SUB_ONE,
		name: 'Basic',
		price: 9.99,
		users: 1,
		features: [
			{ feature: 'NextJS Boilerplate', active: true },
			{ feature: 'user notifications system', active: true },
			{ feature: 'Dashboard analytics', active: true },
			{ feature: 'User session tracking', active: true },
			{ feature: 'OAuth Authentication', active: true },
			{ feature: 'Stunning landing page', active: true },
			{ feature: 'Integrated Contentful blog', active: true },
			{ feature: 'Dashboard admin panel', active: true },
			{ feature: 'Resend email integration', active: true },
			{ feature: 'Stripe one time and subscription payments', active: true },
			{ feature: '1 user allowed in team', active: true },
			{ feature: 'Basic support', active: true },
			{ feature: 'Unlimited storage', active: false },
			{ feature: 'Weekly news updates', active: false },
		],
	},

	pro: {
		type: 'subscription',
		stripePricingId: process.env.NEXT_PUBLIC_STRIPE_SUB_TWO,
		name: 'Pro',
		price: 24.99,
		users: 5,
		features: [
			{ feature: 'NextJS Boilerplate', active: true },
			{ feature: 'user notifications system', active: true },
			{ feature: 'Dashboard analytics', active: true },
			{ feature: 'User session tracking', active: true },
			{ feature: 'OAuth Authentication', active: true },
			{ feature: 'Stunning landing page', active: true },
			{ feature: 'Integrated Contentful blog', active: true },
			{ feature: 'Dashboard admin panel', active: true },
			{ feature: 'Resend email integration', active: true },
			{ feature: 'Stripe one time and subscription payments', active: true },
			{ feature: '5 users allowed in team', active: true },
			{ feature: 'Priority support', active: true },
			{ feature: 'Unlimited storage', active: false },
			{ feature: 'Weekly news updates', active: false },
		],
	},

	enterprise: {
		type: 'subscription',
		stripePricingId: process.env.NEXT_PUBLIC_STRIPE_SUB_THREE,
		name: 'Enterprise',
		price: 49.99,
		users: 1000,
		features: [
			{ feature: 'NextJS Boilerplate', active: true },
			{ feature: 'user notifications system', active: true },
			{ feature: 'Dashboard analytics', active: true },
			{ feature: 'User session tracking', active: true },
			{ feature: 'OAuth Authentication', active: true },
			{ feature: 'Stunning landing page', active: true },
			{ feature: 'Integrated Contentful blog', active: true },
			{ feature: 'Dashboard admin panel', active: true },
			{ feature: 'Resend email integration', active: true },
			{ feature: 'Stripe one time and subscription payments', active: true },
			{ feature: 'Unlimited users allowed in team', active: true },
			{ feature: '24/7 support', active: true },
			{ feature: 'Unlimited storage', active: false },
			{ feature: 'Weekly news updates', active: true },
		],
	},

	starter: {
		type: 'one-time',
		stripePricingId: process.env.NEXT_PUBLIC_STRIPE_ONE_TIME_ONE,
		name: 'Starter',
		price: 38.97,
		features: [
			{ feature: 'NextJS Boilerplate', active: true },
			{ feature: 'user notifications system', active: true },
			{ feature: 'Dashboard analytics', active: true },
			{ feature: 'User session tracking', active: true },
			{ feature: 'OAuth Authentication', active: true },
			{ feature: 'Stunning landing page', active: true },
			{ feature: 'Integrated Contentful blog', active: true },
			{ feature: 'Dashboard admin panel', active: true },
			{ feature: 'Resend email integration', active: true },
			{ feature: 'Stripe one time and subscription payments', active: true },
			{ feature: 'Lifetime updates', active: false },
			{ feature: 'Discord help chat', active: false },
		],
	},

	['full access']: {
		type: 'one-time',
		stripePricingId: process.env.NEXT_PUBLIC_STRIPE_ONE_TIME_TWO,
		name: 'Full access',
		price: 49.99,
		features: [
			{ feature: 'NextJS Boilerplate', active: true },
			{ feature: 'user notifications system', active: true },
			{ feature: 'Dashboard analytics', active: true },
			{ feature: 'User session tracking', active: true },
			{ feature: 'OAuth Authentication', active: true },
			{ feature: 'Stunning landing page', active: true },
			{ feature: 'Integrated Contentful blog', active: true },
			{ feature: 'Dashboard admin panel', active: true },
			{ feature: 'Resend email integration', active: true },
			{ feature: 'Stripe one time and subscription payments', active: true },
			{ feature: 'Lifetime updates', active: true },
			{ feature: 'Discord help chat', active: true },
		],
	},
};

export default plans;
